name: ContraNovo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - libffi
  - openssl
  - pip
  - readline
  - sqlite
  - tk
  - xz
  - zlib
  - pip:
      - absl-py
      - aiohttp
      - aiosignal
      - appdirs
      - arrow
      - async-timeout
      - attrs
      - boto3
      - botocore
      - bravado
      - bravado-core
      - cachetools
      - certifi
      - cffi
      - charset-normalizer
      - click
      - contourpy
      - cryptography
      - cycler
      - deprecated
      - einops
      - fastobo
      - filelock
      - fonttools
      - fqdn
      - frozenlist
      - fsspec
      - future
      - gitdb
      - gitpython
      - google-auth
      - google-auth-oauthlib
      - grpcio
      - h5py
      - idna
      - importlib-metadata
      - importlib-resources
      - isoduration
      - jinja2
      - jmespath
      - joblib
      - jsonpointer
      - jsonref
      - jsonschema
      - jsonschema-specifications
      - kiwisolver
      - lark
      - lightning-utilities
      - llvmlite
      - lmdb
      - lxml
      - markdown
      - markupsafe
      - matplotlib
      - monotonic
      - mpmath
      - msgpack
      - multidict
      - natsort
      - neptune
      - networkx
      - numba
      - numpy
      - oauthlib
      - packaging
      - pandas
      - pillow
      - protobuf
      - psutil
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pygithub
      - pyjwt
      - pynacl
      - pyparsing
      - pyteomics
      - python-dateutil
      - pytorch-lightning==1.9.5
      - pytz
      - pyyaml
      - requests
      - requests-oauthlib
      - rsa
      - s3transfer
      - scikit-learn
      - scipy
      - simplejson
      - six
      - smmap
      - spectrum-utils
      - swagger-spec-validator
      - sympy
      - tensorboard
      - tensorboard-data-server
      - threadpoolctl
      - tqdm
      - typing-extensions
      - tzdata
      - uri-template
      - urllib3
      - webcolors
      - websocket-client
      - werkzeug
      - wrapt
      - yarl
      - zipp
